services:
  server_core:
    build:
      context: .
      dockerfile: ./server_core/Dockerfile
      args:
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: server_core
    ports:
      - "${server_core_PORT}:80"
      - "5173:5173"
    volumes:
      - ../.:/var/www/html
    networks:
      - network_app

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      -  persistent-app:/var/lib/mysql:rw
    depends_on:
      - server_core
    networks:
      - network_app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - network_app

networks:
  network_app:
    name: network_app

volumes:
   persistent-app:
